apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradestore
  labels:
    app: tradestore-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tradestore-app
  template:
    metadata:
      labels:
        app: tradestore-app
    spec:
      containers:
      - name: tradestore
        image: vkoppara/tradestore
        ports:
        - containerPort: 8080
...
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: tradestore-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
